baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Memorial'
theme = 'mainroad' 
mainsections=['post']

[params.logo]
subtitle = "Universidade Federal da Bahia"
subsubtitle = "Memorial da Faculdade de Direito"
image = "images/brasao_da_UFBA.png"
direito = "images/Direito_passado.jpg"
logo_direito = "images/logo_direito.png"

[params]
customCSS = ["css/custom.css"]

[params.memorial]
image = "images/memorial.jpg"


 [[menu.main]]
  name = "Inicial"
  url  = "/"
  weight = 1

  [[menu.main]]
  name = "Hist√≥ria"
  url  = "/post/history"
  weight = 2